---

is_debug: true
listen:
  type: blabla
  bind_ip: 0.0.0.0
  port: 1234
mongodb:
  host: localhost 
  port: 27017
  database: user-service
  auth_db: admin
  username:
  password:
  collection: users